name: hobbie_app
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  percent_indicator: "^2.1.7+2"
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  video_player:
  youtube_player_flutter: ^7.0.0+7
  syncfusion_flutter_gauges: ^18.2.44



dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/


  fonts:
    - family: Roboto
      fonts:

        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

    - family: Grandstander
      fonts:
        - asset: fonts/Grandstander-Regular.ttf
        - asset: fonts/Grandstander-Medium.ttf
          weight: 600
        - asset: fonts/Grandstander-SemiBold.ttf
          weight: 500




